# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestFapesp1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testFapesp1(self):
    self.driver.get("https://fapesp.br/chamadas-html")
    self.driver.set_window_size(1296, 696)
    self.driver.find_element(By.CSS_SELECTOR, ".accordion:nth-child(2) > .accordion__item:nth-child(1) > .accordion-header").click()
    self.driver.find_element(By.LINK_TEXT, "FAPESP-ANR Chamada de Propostas para o Programa “Generic Call for Proposals 2024”").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(22)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".page-body").click()
    self.driver.find_element(By.CSS_SELECTOR, ".page-body").click()
    self.driver.find_element(By.CSS_SELECTOR, ".page-body").click()
    self.driver.find_element(By.CSS_SELECTOR, ".accordion:nth-child(2) > .accordion__item:nth-child(1) > .accordion-header").click()
    self.driver.find_element(By.LINK_TEXT, "Chamada FAPESP - Fundos").click()
  
